# Generated by Django 2.0 on 2020-01-22 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Repositorio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audios',
            options={'verbose_name_plural': 'Archivos de Audio'},
        ),
        migrations.AlterModelOptions(
            name='documentos',
            options={'verbose_name_plural': 'Documentos tales como pdf,xlsx,pptx,etc'},
        ),
        migrations.AlterModelOptions(
            name='imagenes',
            options={'verbose_name_plural': 'Archivos de Imágen'},
        ),
        migrations.AlterModelOptions(
            name='videos',
            options={'verbose_name_plural': 'Archivos de Video'},
        ),
    ]
