# Generated by Django 2.0 on 2020-01-16 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0002_sliderprincipal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliderprincipal',
            name='colorTexto',
            field=models.CharField(default='#000000', max_length=150),
        ),
        migrations.AlterField(
            model_name='sliderprincipal',
            name='posicionHorizontal',
            field=models.CharField(choices=[('0', 'Izquierda'), ('800', 'Derecha'), ('400', 'Centro')], default='0', max_length=120),
        ),
        migrations.AlterField(
            model_name='sliderprincipal',
            name='posicionVertical',
            field=models.CharField(choices=[('0px', '10px'), ('100px', '100px'), ('200px', '200px'), ('200', 'Centro'), ('300px', '300px'), ('400px', '400px')], default='0px', max_length=120),
        ),
        migrations.AlterField(
            model_name='sliderprincipal',
            name='texto',
            field=models.TextField(blank=True, help_text='Puede separa por renglones', null=True),
        ),
    ]
