# Generated by Django 2.0 on 2020-01-16 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0003_auto_20200116_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='sliderprincipal',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
