# Generated by Django 2.0 on 2020-01-16 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0004_sliderprincipal_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliderprincipal',
            name='posicionHorizontal',
            field=models.CharField(choices=[('', 'Izquierda'), ('680', 'Derecha'), ('400', 'Centro')], default='', max_length=120),
        ),
    ]
