# Generated by Django 2.0 on 2020-01-16 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0007_auto_20200116_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sliderprincipal',
            name='posicionHorizontal',
            field=models.CharField(blank=True, choices=[('100', 'Izquierda'), ('680', 'Derecha'), ('400', 'Centro')], max_length=120, null=True),
        ),
    ]
