# Generated by Django 2.0 on 2020-01-20 18:12

from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0010_radio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aguas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='aguas')),
                ('pagina', froala_editor.fields.FroalaField()),
            ],
            options={
                'verbose_name_plural': 'Empresa de Aguas',
            },
        ),
        migrations.CreateModel(
            name='Transito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='transito')),
                ('pagina', froala_editor.fields.FroalaField()),
            ],
            options={
                'verbose_name_plural': 'Empresa de Transito',
            },
        ),
        migrations.CreateModel(
            name='Turismo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='turismo')),
                ('pagina', froala_editor.fields.FroalaField()),
            ],
            options={
                'verbose_name_plural': 'Empresa de Turismo',
            },
        ),
        migrations.AlterModelOptions(
            name='institucion',
            options={'verbose_name_plural': '1. Institución'},
        ),
        migrations.AlterModelOptions(
            name='radio',
            options={'verbose_name_plural': 'Empresa de Radio'},
        ),
        migrations.AlterModelOptions(
            name='sliderprincipal',
            options={'verbose_name_plural': '2. Slider de Imágenes'},
        ),
        migrations.AlterField(
            model_name='radio',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='radio'),
        ),
    ]
