# Generated by Django 2.0 on 2020-01-20 18:35

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0012_directorio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directorio',
            options={'verbose_name_plural': '3. Administración'},
        ),
        migrations.AddField(
            model_name='directorio',
            name='mensaje_principal',
            field=froala_editor.fields.FroalaField(blank=True, null=True),
        ),
    ]
