# Generated by Django 2.0 on 2020-01-20 18:52

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0013_auto_20200120_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='institucion',
            name='color',
            field=colorfield.fields.ColorField(blank=True, max_length=18, null=True),
        ),
    ]
