# Generated by Django 2.0 on 2020-01-20 19:00

from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0015_remove_institucion_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='proyectos')),
                ('portada', models.ImageField(blank=True, null=True, upload_to='proyectos/portada')),
                ('titulo', models.CharField(max_length=60)),
                ('descripcion', froala_editor.fields.FroalaField()),
            ],
            options={
                'verbose_name_plural': '4. Futuros Proyectos',
            },
        ),
    ]
