# Generated by Django 2.0 on 2020-01-21 17:25

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0017_auto_20200121_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='institucion',
            name='mision',
            field=froala_editor.fields.FroalaField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institucion',
            name='vision',
            field=froala_editor.fields.FroalaField(blank=True, null=True),
        ),
    ]
