# Generated by Django 2.0 on 2020-01-21 17:35

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0018_auto_20200121_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='institucion',
            name='objetivos',
            field=froala_editor.fields.FroalaField(blank=True, null=True),
        ),
    ]
