# Generated by Django 2.0 on 2020-01-21 20:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0019_institucion_objetivos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institucion',
            name='mision',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='institucion',
            name='objetivos',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='institucion',
            name='vision',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
