# Generated by Django 2.0 on 2020-01-22 12:01

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0020_auto_20200121_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aguas',
            name='pagina',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='directorio',
            name='datos_informativos',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='directorio',
            name='mensaje_principal',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='descripcion',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='radio',
            name='pagina',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='transito',
            name='pagina',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='turismo',
            name='pagina',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
