# Generated by Django 2.0 on 2020-01-22 13:29

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0021_auto_20200122_0701'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectos',
            name='color_transiscion',
            field=colorfield.fields.ColorField(default='#fffff', max_length=18),
        ),
        migrations.AlterField(
            model_name='proyectos',
            name='imagen',
            field=models.ImageField(help_text='Imagen de 585x480', upload_to='proyectos'),
        ),
    ]
