# Generated by Django 2.0 on 2020-01-22 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0022_auto_20200122_0829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyectos',
            name='color_transiscion',
        ),
    ]
