# Generated by Django 2.0 on 2020-01-22 14:52

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0023_remove_proyectos_color_transiscion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zonas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('thumbail', models.ImageField(upload_to='turismo/thumbail')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='turismo')),
                ('pagina', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name_plural': 'Zonas y Turismo en el Cantón',
            },
        ),
    ]
