# Generated by Django 2.0 on 2020-01-22 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0024_zonas'),
    ]

    operations = [
        migrations.AddField(
            model_name='turismo',
            name='visitas',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='zonas',
            name='visitas',
            field=models.IntegerField(default=1),
        ),
    ]
