# Generated by Django 2.0 on 2020-01-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0026_auto_20200123_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='convocatorias',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
