# Generated by Django 2.0 on 2020-01-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0028_convocatorias_visitas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convocatorias',
            name='visitas',
            field=models.IntegerField(default=1),
        ),
    ]
