# Generated by Django 2.0 on 2020-01-23 13:31

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0029_auto_20200123_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectos',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectos',
            name='fehca_finalizacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyectos',
            name='requisitos',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
