# Generated by Django 2.0 on 2020-01-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0032_noticias_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='noticias/banner'),
        ),
        migrations.AlterField(
            model_name='noticias',
            name='imagen',
            field=models.ImageField(help_text='Imagen de 585 x 480', upload_to='noticias'),
        ),
    ]
