# Generated by Django 2.0 on 2020-01-23 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0033_auto_20200123_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='institucion',
            name='facebook',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='institucion',
            name='google_plus',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='institucion',
            name='twitter',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='institucion',
            name='youtube',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
