# Generated by Django 2.0 on 2020-01-23 18:00

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0036_empresas_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresas',
            name='color_slide',
            field=colorfield.fields.ColorField(default='#ff441', max_length=18),
        ),
    ]
