# Generated by Django 2.0 on 2020-01-23 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0037_empresas_color_slide'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresas',
            name='icono',
            field=models.CharField(choices=[('icon-truck', 'icon-truck'), ('', ''), ('', ''), ('', ''), ('', ''), ('', ''), ('', '')], default='', max_length=120),
            preserve_default=False,
        ),
    ]
