# Generated by Django 2.0 on 2020-01-23 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0038_empresas_icono'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lotaip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(default=2019)),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField()),
                ('archivo', models.FileField(upload_to='lotaip')),
            ],
            options={
                'verbose_name_plural': '6. Cumplimiento LOTAIP',
            },
        ),
        migrations.AlterField(
            model_name='empresas',
            name='icono',
            field=models.CharField(choices=[('icon-truck', 'icon-truck'), ('icon-truck2', 'icon-truck2'), ('icon-microphone', 'icon-microphone'), ('icon-earth', 'icon-earth'), ('icon-earth2', 'icon-earth2'), ('icon-disk', 'icon-disk'), ('icon-disk2', 'icon-disk2')], max_length=120),
        ),
    ]
