# Generated by Django 2.0 on 2020-01-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0039_auto_20200123_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='lotaip',
            name='mes',
            field=models.IntegerField(default=1),
        ),
    ]
