# Generated by Django 2.0 on 2020-01-23 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0040_lotaip_mes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lotaip',
            old_name='anio',
            new_name='periodo',
        ),
    ]
