# Generated by Django 2.0 on 2020-01-23 20:28

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0042_auto_20200123_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='RencionCuentas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.IntegerField(default=2020)),
                ('proceso', ckeditor_uploader.fields.RichTextUploadingField()),
                ('preguntas', models.FileField(upload_to='rendicionCuentas/2020')),
                ('acta', models.FileField(upload_to='rendicionCuentas2020')),
                ('invitacion', models.ImageField(upload_to='rendicionCuentas2020')),
                ('registro_asistencia', models.FileField(upload_to='rendicionCuentas2020')),
            ],
            options={
                'verbose_name_plural': 'Proceso de Rención de cuentas',
            },
        ),
    ]
